#runtime: nodejs
#service: api
#handlers:
#  - url: /.*
#    script: auto
#    secure: always
#
#env: flex
#manual_scaling:
#  instances: 1
#resources:
#  cpu: 1
#  memory_gb: 0.5
#  disk_size_gb: 10
#

runtime: nodejs12
service: api
handlers:
  - url: /.*
    script: auto
    secure: always

# 執行個體等級設定值
instance_class: F4
